# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

stages:
  - dockerize
    
dockerize:
  stage: dockerize
  tags:
    - um-cds
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:1.0" .
    - docker push "$CI_REGISTRY_IMAGE/backend:1.0"
  only:
    - master